# -*- coding: utf-8 -*-
"""ImersãoPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gn1p_Ixa5lpxXIgqFTWRxFVOSnxgxFdm
"""

import pandas as pd
import plotly.express as px

df_principal = pd.read_excel("/content/Imersão Python - Tabela de ações.xlsx", sheet_name="Principal")
df_principal

df_total_de_acoes = pd.read_excel("/content/Imersão Python - Tabela de ações.xlsx", sheet_name="Total_de_acoes")
df_total_de_acoes

df_chatgpt = pd.read_excel("/content/Imersão Python - Tabela de ações.xlsx", sheet_name="ChatGPT")
df_chatgpt

df_ticker = pd.read_excel("/content/Imersão Python - Tabela de ações.xlsx", sheet_name="Ticker")
df_ticker

df_principal = df_principal[['Ativo', 'Data', 'Último (R$)', 'Var. Dia (%)']].copy()
df_principal

df_principal = df_principal.rename(columns={'Último (R$)':'valor_final', 'Var. Dia (%)':'var_dia_pct'}).copy()
df_principal

df_principal['var_pct'] = df_principal['var_dia_pct']/100
df_principal['valor_inicial'] = df_principal['valor_final']/(df_principal['var_pct']+1)
df_principal

df_principal = df_principal.merge(df_total_de_acoes, left_on='Ativo', right_on='Código', how='left')
df_principal

df_principal = df_principal.drop(columns=['Código'])
df_principal

df_principal['variacao_rs'] = (df_principal['valor_final'] - df_principal['valor_inicial'])*df_principal['Qtde. Teórica']
df_principal

"""Formata os floats para apenas 2 decimais"""

pd.options.display.float_format = '{:.2f}'.format
df_principal

"""Muda a coluna Qtd. Teorica para o tipo inteiro e renomeia ela"""

df_principal['Qtde. Teórica'] = df_principal['Qtde. Teórica'].astype(int)
df_principal = df_principal.rename(columns={'Qtde. Teórica':'qtd_teorica'}).copy()
df_principal

df_principal['Resultado'] = df_principal['variacao_rs'].apply(lambda x: 'Subiu' if x > 0 else ('Desceu' if x < 0 else 'Estável'))
df_principal

df_principal = df_principal.merge(df_ticker, left_on='Ativo', right_on='Ticker', how='left')
df_principal = df_principal.drop(columns=['Ticker'])
df_principal

df_principal = df_principal.merge(df_chatgpt, left_on='Nome', right_on='Nome Empresa', how='left')
df_principal = df_principal.drop(columns=['Nome Empresa'])
df_principal

df_principal = df_principal.rename(columns={'Idade (anos)':'Idade'}).copy()
df_principal

df_principal['cat_idade'] = df_principal['Idade'].apply(lambda x: 'Mais de 100' if x > 100 else ('Menos de 50' if x < 50 else 'Entre 50 e 100'))
df_principal

maior = df_principal['variacao_rs'].max()
menor = df_principal['variacao_rs'].min()
media = df_principal['variacao_rs'].mean()

media_subiu = df_principal[df_principal['Resultado'] == 'Subiu']['variacao_rs'].mean()
media_desceu = df_principal[df_principal['Resultado'] == 'Desceu']['variacao_rs'].mean()

df_principal_subiu = df_principal[df_principal['Resultado'] == 'Subiu']
df_principal_subiu

df_analise_segmento = df_principal_subiu.groupby('Segmento')['variacao_rs'].sum().reset_index()
df_analise_segmento

df_analise_saldo = df_principal.groupby('Resultado')['variacao_rs'].sum().reset_index()
df_analise_saldo

fig = px.bar(df_analise_saldo, x = 'Resultado', y = 'variacao_rs', text = 'variacao_rs', title = 'Variação Reais por Resultado')
fig.show()

fig = px.pie(df_principal_subiu, values='variacao_rs', names='Segmento', title='Variação de quem subiu versus segmento')
fig.show()